apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: build-image-and-push-
spec:
  arguments:
    parameters:
      - name: model-version
        value: "%MODEL_VERSION%"
      - name: github-user
        value: "%GITHUB_USER%"
      - name: github-token
        value: "%GITHUB_TOKEN%"
  entrypoint: build-steps
  templates:
    - arguments: {}
      inputs: {}
      metadata: {}
      name: build-steps
      outputs: {}
      steps:
        - - arguments:
              parameters:
                - name: cmdargs
                  value: "curl -s activity-monitor.default.svc.cluster.local:80/?'(ARGO) build-image-and-push-using-docksock-wf run for {{workflow.parameters.model-version}}' > /dev/null"
            name: activity-monitor
            template: image-builder
        - - arguments:
              parameters:
                - name: cmdargs
                  value: "until docker ps; do sleep 3; done; set -x && cd /work/model-source-files/models/simple-model && make MODEL_VERSION={{workflow.parameters.model-version}} build_model_image && docker images && docker images | grep simple-model && make MODEL_VERSION={{workflow.parameters.model-version}} push_to_registry"
            name: build-image
            template: image-builder
        - - arguments:
              parameters:
                - name: cmdargs
                  value: "set -x && cd /work/k8s-manifest-files && make -f Makefile.ci update_model_manifest MODEL_VERSION={{workflow.parameters.model-version}} && git status -s && git config user.email gsunner2000@gmail.com && git commit --allow-empty -m 'auto version update ({{workflow.parameters.model-version}})' demo-manifests/model.yaml && git push"
            name: update-manifest
            template: manifest-updater
    - arguments: {}
      container:
        args:
          - '{{inputs.parameters.cmdargs}}'
        command:
          - sh
          - -c
        image: gsunner/s2i-tools:0.1
        name: ""
        resources: {}
        volumeMounts:
          - mountPath: /var/run/docker.sock
            name: docker-sock-volume
      inputs:
        artifacts:
          - git:
              repo: "https://{{workflow.parameters.github-user}}:{{workflow.parameters.github-token}}@github.com/{{workflow.parameters.github-user}}/cicd-demo-model-source-files.git"
              revision: master
            name: model-source-files
            path: /work/model-source-files
        parameters:
          - name: cmdargs
      metadata: {}
      name: image-builder
      outputs: {}
    - arguments: {}
      container:
        args:
          - '{{inputs.parameters.cmdargs}}'
        command:
          - sh
          - -c
        image: seldonio/k8s-deployer:k8s_v1.9.0
        name: ""
        resources: {}
      inputs:
        artifacts:
          - git:
              repo: "https://{{workflow.parameters.github-user}}:{{workflow.parameters.github-token}}@github.com/{{workflow.parameters.github-user}}/cicd-demo-k8s-manifest-files.git"
              revision: master
            name: k8s-manifest-files
            path: /work/k8s-manifest-files
        parameters:
          - name: cmdargs
      metadata: {}
      name: manifest-updater
      outputs: {}
  volumes:
    - hostPath:
        path: /var/vcap/data/sys/run/docker/docker.sock
        type: File
      name: docker-sock-volume